<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
    <OutputType>Library</OutputType>
    <!--Turn on warnings for unused values (arguments and let bindings) -->
    <OtherFlags>$(OtherFlags) --warnon:1182</OtherFlags>
    <NoWarn>FS0988</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AutoOpen.fs" />
    <Compile Include="MergeTests.fs" />
    <Compile Include="BindingVmHelpersTests.fs" />
    <Compile Include="DynamicViewModelTests.fs" />
    <Compile Include="StaticViewModelTests.fs" />
    <Compile Include="BindingTests.fs" />
    <Compile Include="UtilsTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Interop.Dynamic" />
    <PackageReference Include="Hedgehog" />
    <PackageReference Include="Hedgehog.Experimental" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Unquote" />
    <PackageReference Include="xunit.core" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elmish.Uno\Elmish.Uno.fsproj" />
  </ItemGroup>

</Project>
