<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Solution.Build.props" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>$(RootNamespace).Tests</RootNamespace>
    <AssemblyName>$(AssemblyBaseName).Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <OutputType>Library</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>
    <!--Turn on warnings for unused values (arguments and let bindings) -->
    <OtherFlags>$(OtherFlags) --warnon:1182</OtherFlags>
    <NoWarn>FS0988</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="InternalUtils.fs" />
    <Compile Include="MergeTests.fs" />
    <Compile Include="ViewModelTests.fs" />
    <Compile Include="BindingTests.fs" />
    <Compile Include="UtilsTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Interop.Dynamic" />
    <PackageReference Include="Hedgehog" />
    <PackageReference Include="Hedgehog.Experimental" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Unquote" />
    <PackageReference Include="xunit.core" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elmish.Uno\Elmish.Uno.fsproj" />
  </ItemGroup>

</Project>
