<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Solution.Build.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net6.0-windows10.0.22000.0</TargetFrameworks>
    <TargetPlatformMinVersion Condition="$(TargetFramework.StartsWith('net6.0-windows10'))">10.0.17763.0</TargetPlatformMinVersion>
    <AssemblyName>$(AssemblyBaseName)</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugType>Embedded</DebugType>
    <EmbedAllSources>True</EmbedAllSources>
    <Description>F# bindings for using Elmish in Uno</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/XperiAndri/Elmish.Uno</PackageProjectUrl>
    <PackageTags>Uno F# fsharp Elmish Elm</PackageTags>
    <PackageIcon>elmish-uno-logo-128x128.png</PackageIcon>
    <Version>1.0.0</Version>
    <PackageReleaseNotes></PackageReleaseNotes>-->

    <!--Turn on warnings for unused values (arguments and let bindings) -->
    <OtherFlags>$(OtherFlags) --warnon:1182</OtherFlags>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.StartsWith('net6.0-windows10'))">
    <DefineConstants>$(DefineConstants);__UWP__</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="elmish-uno-logo-128x128.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Elmish.Uno.Tests</_Parameter1>
    </AssemblyAttribute>
    <Compile Include="InternalUtils.fs" />
    <Compile Include="InternalTypes.fs" />
    <Compile Include="Config.fs" />
    <Compile Include="Binding.fs" />
    <Compile Include="Utils.fs" />
    <Compile Include="DynamicCustomProperty.fs" />
    <Compile Include="ViewModel.fs" />
    <Compile Include="ViewModelModule.fs" />
    <Compile Include="Program.fs" />
    <Compile Include="Navigation.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elmish" VersionOverride="[3.0.3, 4)" />
    <PackageReference Include="FSharp.Collections.Immutable" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Condition="$(TargetFramework.StartsWith('net6.0-windows10'))" />
    <!--<PackageReference Include="Microsoft.WindowsAppSDK" GeneratePathProperty="true" Condition="$(TargetFramework.StartsWith('net6.0-windows10'))" />-->
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Condition="$(TargetFramework.StartsWith('net6.0-windows10'))" />
    <PackageReference Include="Uno.Core" />
    <PackageReference Include="Uno.WinUI" Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net6.0' " />
  </ItemGroup>

  <Target Name="XamlPreCompile" Condition="$(TargetFramework.StartsWith('net6.0-windows10'))" />

  <!--<Target Name="FixReferenceCopyLocalPaths" BeforeTargets="ResolvePackageAssets" Condition="$(TargetFramework.StartsWith('net6.0-windows10'))">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="$(PkgMicrosoft_WindowsAppSDK)\build\..\runtimes\lib\native\AnyCPU\Microsoft.WindowsAppRuntime.Bootstrap.dll"/>
    </ItemGroup>
  </Target>-->

</Project>
