name: Continuous Integration

on:
  push:
    branches: [ master, v3 ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install .NET SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore src/Elmish.WPF.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release src/Elmish.Uno.sln

    - name: Test
      run: dotnet test --no-build --configuration Release src/Elmish.Uno.Tests/Elmish.Uno.Tests.fsproj

    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: "src/Elmish.WPF/Elmish.WPF.fsproj"
        PACKAGE_NAME: "Elmish.WPF"
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
