name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install .NET SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore NuGet Packages
      run: nuget restore 'src\\Elmish.Uno.sln' -ConfigFile 'NuGet.Config'

    - name: Build
      run: msbuild 'src\\Elmish.Uno.sln' /t:Rebuild /p:Configuration=Release /p:Platform='Any CPU'

    - name: Test
      run: dotnet test --no-build --configuration Release src/Elmish.Uno.Tests/Elmish.Uno.Tests.fsproj
